CH04
ecolotta/rspec_app_exam pull request #1
Opened 2021-02-05 06:47 UTC by ecolotta

[RSpec編] 04_未完成のテストコード修正
課題完了したのでご確認をお願いいたします。

2021-02-05 06:54 UTC, yuji91 requested changes
何点か指摘しました。
指摘事項ごとにコミットの単位は分けてください。

2021-02-05 06:54 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { 'done' }
Symbol型として記載しましょう。Enumの値であることを明示できます。
```suggestion
      status { :done }
```

2021-02-05 06:54 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
Factoryに`association`をつけると省略可能となります。
```suggestion
  let(:task) { create(:task) }
```

2021-02-05 06:54 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d'))
失敗例のPRは確認しましたでしょうか？
この修正方法には問題があります。

2021-02-05 06:54 UTC, yuji91 commented on spec/system/task_spec.rb
> +      #  byebug
不要なコメントが残ったままです。
レビュー依頼前に以下の差分を確認すると良いでしょう。
https://github.com/ecolotta/rspec_app_exam/pull/1/files

2021-02-05 06:54 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id, title: 'delete_test')
テストデータのタイトルにテストが依存しているため、この部分の記載は戻した上で、テストをどう修正すれば良いか考え直してください。

2021-02-06 01:31 UTC, ecolotta commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
444e5f2で修正しました。

2021-02-06 01:31 UTC, ecolotta commented on spec/factories/tasks.rb
> +      status { 'done' }
b7afa49で修正しました。

2021-02-06 01:31 UTC, ecolotta commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d'))
a17888fで修正しました。

2021-02-06 01:31 UTC, ecolotta commented on spec/system/task_spec.rb
> +      #  byebug
ed16b5fで修正しました。

2021-02-06 01:32 UTC, ecolotta commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id, title: 'delete_test')
adee737で修正しました。

2021-02-06 02:33 UTC, yuji91 reviewed
修正の際は`Fix:`などのプレフィックスをコミットメッセージにつけると後から見やすいと思います。
https://www.tam-tam.co.jp/tipsnote/program/post16686.html

2021-02-06 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done_project, project_id: project.id)
この部分もassociationの設定により省略可能ですね。
```suggestion
        task = create(:task, :done_project)
```

2021-02-06 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('tr')).not_to have_content task.title
trではなく、画面上で色付けされている範囲を指定すると良いかと思います。

2021-02-06 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task)
ローカル変数でテストデータを定義するよりは、let!でFactoryを事前に作成する形の方が良いです。
let!であれば、複数のテストケースで作成するデータをまとめて定義するなど汎用性が高いです。

2021-02-06 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +      fit 'Taskが削除されること' do
focus設定がついたままのコミットとなっています。
```suggestion
      it 'Taskが削除されること' do
```

2021-02-06 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
短く1行で記載できるかと思います。
```suggestion
       switch_to_window(windows.last)
```

2021-02-06 09:10 UTC, ecolotta commented on spec/system/task_spec.rb
> +        task = create(:task, :done_project, project_id: project.id)
d0ddab3 で修正しました。

2021-02-06 09:10 UTC, ecolotta commented on spec/system/task_spec.rb
> +        expect(find('tr')).not_to have_content task.title
1bc6949 で修正しました。

2021-02-06 09:11 UTC, ecolotta commented on spec/system/task_spec.rb
> +      fit 'Taskが削除されること' do
b761505 で修正しました。

2021-02-06 09:11 UTC, ecolotta commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
1c97504 で修正しました。

2021-02-06 09:21 UTC, ecolotta commented on spec/system/task_spec.rb
> +        task = create(:task)
b8b03d4 で修正しました。
この変更であらかじめtaskが一つ作成されている状態になったため'Taskが新規作成されること'のテストが通らなくなりました。
先に作成されている前提でテストが通るように修正しましたが適切でしょうか。

2021-02-06 10:06 UTC, yuji91 requested changes
2点コメントしました。

2021-02-06 10:06 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :done_project do
このtrait名だと関連しているProjectが完了しているように思えますが、完了しているのは単体のtaskです。
誤解を生まないようにprojectという単語は外してしまった方が良いでしょう。
```suggestion
    trait :done do
```

2021-02-06 10:06 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let!(:task) { create(:task) }
タスクの全テストケースでテストデータを登録する必要はないと思います。
そのためこの階層のdescribe直下でlet!を使うことは通常しません。

テストデータの登録があらかじめ必要なテストケースのみにlet!を記載するようにしてください。

2021-02-06 10:07 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task)
https://github.com/ecolotta/rspec_app_exam/pull/1#discussion_r571401254 でコメントしたのでご確認ください。

2021-02-08 06:25 UTC, ecolotta commented on spec/system/task_spec.rb
> +  let!(:task) { create(:task) }
ありがとうございます。
describeごとにletを記載をするように変更しました。
cc600fc で修正しました。

2021-02-08 06:25 UTC, ecolotta commented on spec/factories/tasks.rb
> +    trait :done_project do
a6169ff で修正しました。

2021-02-08 08:58 UTC, yuji91 requested changes
letとlet!の使い分けについて、まだイメージが持てていないかと思います。

let --> Factoryの処理などを変数として定義できる。呼び出された場合に実行される。
let! --> 定義した処理はテストケースの実行前に評価される。変数名での呼び出しによって作成したテストデータを参照する事ができる。

そのため、letは各テストケースの最上部に1回のみ定義すれば良いです。
let!は必要のあるテストケースに絞って定義する形になります。

以上を考慮して、もう一度考え直してみてください。

2021-02-08 10:08 UTC, ecolotta commented on spec/system/task_spec.rb
> +  let!(:task) { create(:task) }
ce0d576 で再度修正しました。
結果的に[ここで](https://github.com/ecolotta/rspec_app_exam/pull/1#discussion_r571342650)ご指摘いただいているtask = create(:task)の変数定義と同じようなことをやっている気がするんですが、
 typoにすぐ気づける点やローカル変数をそのままletに置き換えられる点からテストではlet!を使う方が望ましいという認識でよろしいでしょうか。。（ここを参考にしました　https://qiita.com/jnchito/items/cdd9eef2ed193267c651）

2021-02-08 10:25 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let!(:task) { create(:task) }
> テストではlet!を使う方が望ましいという認識でよろしいでしょうか

前提として`let`と`let!`は別物で、テストケース実行時のテストデータ生成のタイミングが異なります。
そのため状況で都度どちらを記載するべきかは異なります。

それを踏まえた上で、letとlet!の記法を使う方が望ましいかという点については、以下のメリットがあるためこの課題で取り入れています。
- letで共通化することにより、全体のコード量を削減することができる
- letに慣れてしまえば、他のテストコードの記載に集中できるため可読性が向上する
- letでテストコードが書かれている現場に入った際には合わせて記載する必要が出るため、少なくとも書けるようにはなっておかなければならない

2021-02-08 10:26 UTC, yuji91 requested changes
残り1点、対応をお願いします。

2021-02-08 10:26 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
この変数宣言はlet!の記載で代用可能です。どこに記載するのが適切かについても考えて変更してみてください。

2021-02-08 10:37 UTC, ecolotta commented on spec/system/task_spec.rb
> +  let!(:task) { create(:task) }
ありがとうございます。
今回だと、一つのテストに対してtaskを作成するためになるので変数でも変わらない気もしており、let!とローカル変数どちらを使った方がいいかという意図で質問をさせていただいていました。

2021-02-08 10:58 UTC, ecolotta commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
a9d524c で修正しました。
他のテストで使うこともあると考えdescribe 'Task編集' do以下に記載しましたが適切でしょうか。
あらかじめ必要なデータではないためlet!で記載する必要性がわかりませんでした。

2021-02-08 11:06 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
「既にステータスが完了のタスクのステータスを変更した場合」のテストケースなので、テストデータをあらかじめ用意しておくことは必要だと思います。

しかし後続のvisit の引数でletを呼び出しているため、自分が指摘した`let!`の記載は使わずに現状の`let`の定義をvisitの引数で呼ぶ形で良いと思います。

記載場所もその認識で問題ないと思います。

2021-02-08 11:08 UTC, yuji91 approved these changes
修正確認したので、これでLGTMです！

2021-02-09 01:42 UTC, ecolotta commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
ありがとうございます。

2021-02-09 01:42 UTC, merged